title: Jingxuan's Homepage
page-top-title: Jingxuan 
top-section-bg-text: Math Of Computation
home-subtitle: Jingxuan Li &ensp;|&ensp;|&ensp;李婧瑄
copyright-text: '&copy; Sen Li 2023-2024. All Rights Reserved.'
